site_name: Rosework
site_url: https://rbx-rosework.github.io/docs

nav:
    - Home:
        - index.md
    - Getting Started:
        - getting_started
    - API Reference:
        - api_reference/index.md
        - Core: api_reference/core
        - Singletons: api_reference/singleton
        - Component: api_reference/component
        - Tool: api_reference/tool
        - State: api_reference/state
        - Submodule System: api_reference/sms

theme:
    name: material
    custom_dir: docs/overrides
    logo: res/img/rosework-logo.svg
    favicon: res/img/rosework-logo.svg
    icon:
        repo: fontawesome/brands/github
    features:
        - header.autohide
        - navigation.tabs
        - navigation.instant
        - navigation.indexes
    pallete:
        primary: black
    font:
        text: Inter
        code: JetBrains Mono

extra_css:
    - css/index.css
    
markdown_extensions:
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences

repo_url: https://github.com/rbx-rosework/core
repo_name: Rosework/Core

extra:
    generator: false
copyright: Copyright &copy; 2022 Roseau Corporation
