site_name: Rosework
site_url: https://rbx-rosework.github.io/docs

nav:
    - Home: index.md

theme:
    name: material
    icon:
        repo: fontawesome/brands/github
    features:
        - header.autohide
        - navigation.tabs
    pallete:
        scheme: slate
    font:
        text: Inter
        code: JetBrains Mono

extra_css:
    - css/index.css
    
markdown_extensions:
  - meta

repo_url: https://github.com/rbx-rosework/core
repo_name: Rosework/Core

extra:
    generator: false
copyright: Copyright &copy; 2022 Roseau Corporation
