site_name: Rosework
site_url: https://rbx-rosework.github.io/docs
nav:
    - Home: index.md
theme:
    name: material    name: material
repo_url: https://github.com/rbx-rosework/core
repo_name: Rosework/Core

